-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "city" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP + INTERVAL '7 days',
ALTER COLUMN "endDate" SET DEFAULT CURRENT_TIMESTAMP + INTERVAL '8 days';
